services:
  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    restart: always
    volumes:
      - static_data:/home/app/web/static
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn whatgenderis.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.staging
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.staging.db
  proxy-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_data:
  certs:
  html:
  vhost:
  acme: